# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/flint/Downloads/clion-2017.3.4/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/flint/Downloads/clion-2017.3.4/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/flint/Repos/so2-projekt

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/flint/Repos/so2-projekt

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/flint/Downloads/clion-2017.3.4/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/flint/Downloads/clion-2017.3.4/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/flint/Repos/so2-projekt/CMakeFiles /home/flint/Repos/so2-projekt/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/flint/Repos/so2-projekt/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named so2_projekt

# Build rule for target.
so2_projekt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 so2_projekt
.PHONY : so2_projekt

# fast build rule for target.
so2_projekt/fast:
	$(MAKE) -f CMakeFiles/so2_projekt.dir/build.make CMakeFiles/so2_projekt.dir/build
.PHONY : so2_projekt/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/so2_projekt.dir/build.make CMakeFiles/so2_projekt.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/so2_projekt.dir/build.make CMakeFiles/so2_projekt.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/so2_projekt.dir/build.make CMakeFiles/so2_projekt.dir/main.cpp.s
.PHONY : main.cpp.s

utils/State.o: utils/State.cpp.o

.PHONY : utils/State.o

# target to build an object file
utils/State.cpp.o:
	$(MAKE) -f CMakeFiles/so2_projekt.dir/build.make CMakeFiles/so2_projekt.dir/utils/State.cpp.o
.PHONY : utils/State.cpp.o

utils/State.i: utils/State.cpp.i

.PHONY : utils/State.i

# target to preprocess a source file
utils/State.cpp.i:
	$(MAKE) -f CMakeFiles/so2_projekt.dir/build.make CMakeFiles/so2_projekt.dir/utils/State.cpp.i
.PHONY : utils/State.cpp.i

utils/State.s: utils/State.cpp.s

.PHONY : utils/State.s

# target to generate assembly for a file
utils/State.cpp.s:
	$(MAKE) -f CMakeFiles/so2_projekt.dir/build.make CMakeFiles/so2_projekt.dir/utils/State.cpp.s
.PHONY : utils/State.cpp.s

utils/StateRaport.o: utils/StateRaport.cpp.o

.PHONY : utils/StateRaport.o

# target to build an object file
utils/StateRaport.cpp.o:
	$(MAKE) -f CMakeFiles/so2_projekt.dir/build.make CMakeFiles/so2_projekt.dir/utils/StateRaport.cpp.o
.PHONY : utils/StateRaport.cpp.o

utils/StateRaport.i: utils/StateRaport.cpp.i

.PHONY : utils/StateRaport.i

# target to preprocess a source file
utils/StateRaport.cpp.i:
	$(MAKE) -f CMakeFiles/so2_projekt.dir/build.make CMakeFiles/so2_projekt.dir/utils/StateRaport.cpp.i
.PHONY : utils/StateRaport.cpp.i

utils/StateRaport.s: utils/StateRaport.cpp.s

.PHONY : utils/StateRaport.s

# target to generate assembly for a file
utils/StateRaport.cpp.s:
	$(MAKE) -f CMakeFiles/so2_projekt.dir/build.make CMakeFiles/so2_projekt.dir/utils/StateRaport.cpp.s
.PHONY : utils/StateRaport.cpp.s

views/IView.o: views/IView.cpp.o

.PHONY : views/IView.o

# target to build an object file
views/IView.cpp.o:
	$(MAKE) -f CMakeFiles/so2_projekt.dir/build.make CMakeFiles/so2_projekt.dir/views/IView.cpp.o
.PHONY : views/IView.cpp.o

views/IView.i: views/IView.cpp.i

.PHONY : views/IView.i

# target to preprocess a source file
views/IView.cpp.i:
	$(MAKE) -f CMakeFiles/so2_projekt.dir/build.make CMakeFiles/so2_projekt.dir/views/IView.cpp.i
.PHONY : views/IView.cpp.i

views/IView.s: views/IView.cpp.s

.PHONY : views/IView.s

# target to generate assembly for a file
views/IView.cpp.s:
	$(MAKE) -f CMakeFiles/so2_projekt.dir/build.make CMakeFiles/so2_projekt.dir/views/IView.cpp.s
.PHONY : views/IView.cpp.s

views/RawConsoleMainView.o: views/RawConsoleMainView.cpp.o

.PHONY : views/RawConsoleMainView.o

# target to build an object file
views/RawConsoleMainView.cpp.o:
	$(MAKE) -f CMakeFiles/so2_projekt.dir/build.make CMakeFiles/so2_projekt.dir/views/RawConsoleMainView.cpp.o
.PHONY : views/RawConsoleMainView.cpp.o

views/RawConsoleMainView.i: views/RawConsoleMainView.cpp.i

.PHONY : views/RawConsoleMainView.i

# target to preprocess a source file
views/RawConsoleMainView.cpp.i:
	$(MAKE) -f CMakeFiles/so2_projekt.dir/build.make CMakeFiles/so2_projekt.dir/views/RawConsoleMainView.cpp.i
.PHONY : views/RawConsoleMainView.cpp.i

views/RawConsoleMainView.s: views/RawConsoleMainView.cpp.s

.PHONY : views/RawConsoleMainView.s

# target to generate assembly for a file
views/RawConsoleMainView.cpp.s:
	$(MAKE) -f CMakeFiles/so2_projekt.dir/build.make CMakeFiles/so2_projekt.dir/views/RawConsoleMainView.cpp.s
.PHONY : views/RawConsoleMainView.cpp.s

workers/BaseSeparator.o: workers/BaseSeparator.cpp.o

.PHONY : workers/BaseSeparator.o

# target to build an object file
workers/BaseSeparator.cpp.o:
	$(MAKE) -f CMakeFiles/so2_projekt.dir/build.make CMakeFiles/so2_projekt.dir/workers/BaseSeparator.cpp.o
.PHONY : workers/BaseSeparator.cpp.o

workers/BaseSeparator.i: workers/BaseSeparator.cpp.i

.PHONY : workers/BaseSeparator.i

# target to preprocess a source file
workers/BaseSeparator.cpp.i:
	$(MAKE) -f CMakeFiles/so2_projekt.dir/build.make CMakeFiles/so2_projekt.dir/workers/BaseSeparator.cpp.i
.PHONY : workers/BaseSeparator.cpp.i

workers/BaseSeparator.s: workers/BaseSeparator.cpp.s

.PHONY : workers/BaseSeparator.s

# target to generate assembly for a file
workers/BaseSeparator.cpp.s:
	$(MAKE) -f CMakeFiles/so2_projekt.dir/build.make CMakeFiles/so2_projekt.dir/workers/BaseSeparator.cpp.s
.PHONY : workers/BaseSeparator.cpp.s

workers/BaseWorker.o: workers/BaseWorker.cpp.o

.PHONY : workers/BaseWorker.o

# target to build an object file
workers/BaseWorker.cpp.o:
	$(MAKE) -f CMakeFiles/so2_projekt.dir/build.make CMakeFiles/so2_projekt.dir/workers/BaseWorker.cpp.o
.PHONY : workers/BaseWorker.cpp.o

workers/BaseWorker.i: workers/BaseWorker.cpp.i

.PHONY : workers/BaseWorker.i

# target to preprocess a source file
workers/BaseWorker.cpp.i:
	$(MAKE) -f CMakeFiles/so2_projekt.dir/build.make CMakeFiles/so2_projekt.dir/workers/BaseWorker.cpp.i
.PHONY : workers/BaseWorker.cpp.i

workers/BaseWorker.s: workers/BaseWorker.cpp.s

.PHONY : workers/BaseWorker.s

# target to generate assembly for a file
workers/BaseWorker.cpp.s:
	$(MAKE) -f CMakeFiles/so2_projekt.dir/build.make CMakeFiles/so2_projekt.dir/workers/BaseWorker.cpp.s
.PHONY : workers/BaseWorker.cpp.s

workers/WoodchopperWorker.o: workers/WoodchopperWorker.cpp.o

.PHONY : workers/WoodchopperWorker.o

# target to build an object file
workers/WoodchopperWorker.cpp.o:
	$(MAKE) -f CMakeFiles/so2_projekt.dir/build.make CMakeFiles/so2_projekt.dir/workers/WoodchopperWorker.cpp.o
.PHONY : workers/WoodchopperWorker.cpp.o

workers/WoodchopperWorker.i: workers/WoodchopperWorker.cpp.i

.PHONY : workers/WoodchopperWorker.i

# target to preprocess a source file
workers/WoodchopperWorker.cpp.i:
	$(MAKE) -f CMakeFiles/so2_projekt.dir/build.make CMakeFiles/so2_projekt.dir/workers/WoodchopperWorker.cpp.i
.PHONY : workers/WoodchopperWorker.cpp.i

workers/WoodchopperWorker.s: workers/WoodchopperWorker.cpp.s

.PHONY : workers/WoodchopperWorker.s

# target to generate assembly for a file
workers/WoodchopperWorker.cpp.s:
	$(MAKE) -f CMakeFiles/so2_projekt.dir/build.make CMakeFiles/so2_projekt.dir/workers/WoodchopperWorker.cpp.s
.PHONY : workers/WoodchopperWorker.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... so2_projekt"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... utils/State.o"
	@echo "... utils/State.i"
	@echo "... utils/State.s"
	@echo "... utils/StateRaport.o"
	@echo "... utils/StateRaport.i"
	@echo "... utils/StateRaport.s"
	@echo "... views/IView.o"
	@echo "... views/IView.i"
	@echo "... views/IView.s"
	@echo "... views/RawConsoleMainView.o"
	@echo "... views/RawConsoleMainView.i"
	@echo "... views/RawConsoleMainView.s"
	@echo "... workers/BaseSeparator.o"
	@echo "... workers/BaseSeparator.i"
	@echo "... workers/BaseSeparator.s"
	@echo "... workers/BaseWorker.o"
	@echo "... workers/BaseWorker.i"
	@echo "... workers/BaseWorker.s"
	@echo "... workers/WoodchopperWorker.o"
	@echo "... workers/WoodchopperWorker.i"
	@echo "... workers/WoodchopperWorker.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

